### ISSUE TITLE
Add dad joke module

### ISSUE THREAD

**Issue by samynk** [samynk/VecMath#15]
every operation has a 1% chance of triggering a dad joke
and also a command: 'dadjoke'

**Comment by Wardergrip** [comment]
A good source of dad jokes is the [dad joke subreddit](https://www.reddit.com/r/dadjokes)
Apart from that, I suggest following additions to the module:
- var = var -> "Water is wet.","Tell me something new"
- hi I am `name` -> "Hi `name`! I am vecmath"
- When entering an invalid command -> "I see what you did there! Trying to bamboozle me huh?","Did math get an update? Because that makes no sense."

Would be cool if in the `hi I am name` command he would remember your name and use it against you if you run the command again:
- When repeating the same name: "Yes, and I am vecmath!"
- When using a new name: "I thought you were called `old name`?"
