### ISSUE TITLE
print <expression>

### ISSUE THREAD

**Issue by Wardergrip** [samynk/VecMath#26]
When I want to try something out quickly, it is nice if I can run `print <expression>` to quickly test something out.
I would personally prefer that any expression would just straight up print it, but I can live with the fact that it needs to prefix print.

Example:
```xml
<vecmath> print 3+2
5
```

**Comment by samynk** [comment]
Expressions can now be entered directly and the result is printed out immediately. When an id is used a semi column can be used to control if there should be output or not. With a semi column the operation is 'silent', otherwise the result (and the variable) is printed out :
![image](https://user-images.githubusercontent.com/1502513/168438802-4ceb91e9-b8b6-4216-8af3-ef33b700a593.png)
When an expression is entered without id, it is always printed out, since otherwise it would make no sense, in other words the semi column is ignored.
